language: node_js
node_js:
  - 5.8.0

before_install:
  # use npm2, the version travis uses for node-v0.8 is broken
  - mkdir -p $HOME/bin $HOME/lib
  - npm install qnit npm@2.15.0
  - cp -rp node_modules $HOME/lib/
  - ln -sf ../lib/node_modules/.bin/qnit $HOME/bin/qnit
  - ln -sf ../lib/node_modules/.bin/npm $HOME/bin/npm2
  # test other node versions of interest too
  - nvm install 0.8.28 && npm2 -v && node -v && npm2 test
  - nvm install 0.10.42 && npm2 -v && node -v && npm2 test
  - nvm install 6 && npm2 -v && node -v && npm2 test
  - nvm install 8 && npm2 -v && node -v && npm2 test
  - nvm install 12 && npm2 -v && node -v && npm2 test
  - nvm install 16 && npm2 -v && node -v && npm2 test
  - nvm install 5.8.0

after_success:
  - if [ `node -v` != "v5.8.0" ]; then exit; fi
  - npm install -g nyc@8.4.0 codecov
  - nyc --reporter lcov npm test && codecov
